[package]
name = "jtrace"
version = "0.1.0"
authors = ["ex0dus-0x <ex0dus@codemuch.tech>"]

[dependencies]
libc = "0.2"
nix = "0.13.0"

clap = "2.33.0"
log = "0.4.6"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
